name: multistage_tandem
description: 可自定义多级联动的 Widget
version: 0.0.1
author: happyldc
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter





